include: lints.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/**/**.config.dart
    - lib/**/**.g.dart
    - lib/**/**.freezed.dart
    - test/**
    - lib/presentation/themes/**
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    # Function
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 40
    # Class
    weight-of-class: 0.33
    # Tech debt
    technical-debt:
      threshold: 1
      todo-cost: 24
      ignore-cost: 8
      ignore-for-file-cost: 24
      as-dynamic-cost: 16
      deprecated-annotations-cost: 24
      file-nullsafety-migration-cost: 16
      unit-type: "hours"
  rules:
    # Dart
    - avoid-nested-conditional-expressions:
        severity: warning
        acceptable-level: 2
    - avoid-non-null-assertion:
        severity: warning
    - avoid-missing-enum-constant-in-map:
        severity: warning
    - avoid-unnecessary-type-assertions:
        severity: warning
    - avoid-unnecessary-type-assertions:
        severity: warning
    - avoid-unnecessary-type-casts:
        severity: warning
    - avoid-unrelated-type-assertions:
        severity: warning
    - avoid-unused-parameters:
        severity: warning
    - binary-expression-operand-order:
        severity: warning
    - no-boolean-literal-compare:
        severity: warning
    - no-equal-arguments:
        severity: warning
    - no-equal-then-else:
        severity: warning
    - no-object-declaration:
        severity: warning
    - prefer-first:
        severity: warning
    - prefer-async-await:
        severity: warning
    - prefer-last:
        severity: warning
    - prefer-trailing-comma:
        severity: warning
    - prefer-match-file-name:
        severity: warning
        exclude:
            - lib/presentation/themes/**
    # Flutter
    - always-remove-listener:
        severity: warning
    - avoid-unnecessary-setstate:
        severity: warning
