name: hdrezka_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  responsive_framework: ^0.2.0
  flutter_native_splash: ^2.2.10+1
  better_player: ^0.0.83
  fluttertoast: ^8.0.9
  infinite_scroll_pagination: ^3.2.0

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Data classes
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0

  # State management
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  async_redux: ^15.0.0

  # Rx
  rxdart: ^0.27.5

  # Api
  retrofit: ^3.0.1+1
  dio: ^4.0.6

  # Storage
  shared_preferences: ^2.0.15

  # Firebase
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  cloud_firestore: ^3.4.4

  # Other
  json_diff: ^0.2.0
  external_video_player_launcher: ^0.0.3
  useful_extensions: ^0.0.1
  speech_to_text: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.4
  dart_code_metrics: ^4.18.3
  retrofit_generator: ^4.0.2
  freezed: ^2.1.0+1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#000000"
  image: assets/icons/hdrezka_text_icon.png
  color_dark: "#000000"
  image_dark: assets/icons/hdrezka_text_icon.png

  android_12:
    image: assets/icons/hdrezka_text_icon.png
    icon_background_color: "#000000"
    image_dark: assets/icons/hdrezka_text_icon.png
    icon_background_color_dark: "#000000"

  web: false
  ios: false

flutter_icons:
  image_path: "assets/icons/hdrezka_icon.png"
  android: false
  remove_alpha_ios: true
  ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: true