name: hdrezka_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get_it: ^7.2.0
  json_annotation: ^4.6.0
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.2
  injectable: ^1.5.3
  responsive_framework: ^0.2.0
  freezed_annotation: ^2.1.0
  rxdart: ^0.27.5
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  async_redux: ^15.0.0
  shared_preferences: ^2.0.15
  infinite_scroll_pagination: ^3.2.0
  json_diff: ^0.2.0
  better_player: ^0.0.83
  external_video_player_launcher: ^0.0.3
  fluttertoast: ^8.0.9
  useful_extensions: ^0.0.1
  bloc_concurrency: ^0.2.0
  speech_to_text: ^5.6.0
  floor: ^1.3.0
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  cloud_firestore: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.4
  dart_code_metrics: ^4.18.3
  retrofit_generator: ^4.0.2
  floor_generator: ^1.3.0
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
