// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXDdljeiB8LAGn3yD6u0OOtCcwuP2OZPg',
    appId: '1:805982787634:android:fa712b614d51a3bcb8442b',
    messagingSenderId: '805982787634',
    projectId: 'hdrezkaapp',
    storageBucket: 'hdrezkaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiCw3vWpla2UC55rd0q1jnyvNxRZklFKk',
    appId: '1:805982787634:ios:ebdc7f591eaf3a52b8442b',
    messagingSenderId: '805982787634',
    projectId: 'hdrezkaapp',
    storageBucket: 'hdrezkaapp.appspot.com',
    iosClientId:
        '805982787634-24g3e9haglrmggppng50gqgej2scr9la.apps.googleusercontent.com',
    iosBundleId: 'com.example.hdrezkaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiCw3vWpla2UC55rd0q1jnyvNxRZklFKk',
    appId: '1:805982787634:ios:ebdc7f591eaf3a52b8442b',
    messagingSenderId: '805982787634',
    projectId: 'hdrezkaapp',
    storageBucket: 'hdrezkaapp.appspot.com',
    iosClientId:
        '805982787634-24g3e9haglrmggppng50gqgej2scr9la.apps.googleusercontent.com',
    iosBundleId: 'com.example.hdrezkaApp',
  );
}
