name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

env:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "3.0.4"
  FLUTTER_PATH: /opt/hostedtoolcache/flutter #ubuntu-latest

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_PATH }}
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@master
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Flutter Doctor
        run: flutter doctor -v
      - name: Flutter Analyze
        run: flutter analyze
      - name: Dart code metrics
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_unused_files: false
      - name: Check Formatting
        run: flutter format --set-exit-if-changed lib
  build_android:
    name: Build Android APK
    needs: [analyze]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_PATH }}
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@master
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Flutter clean
        run: flutter clean
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter build apk
        run: flutter build apk
